In [30]:
import numpy as np

A = np.random.randint(1,11, size=(2,2))
B = np.random.randint(1,11,size=(2,2))

print (A)
print (B)


[[10  6]
 [ 2  5]]
[[ 7 10]
 [ 4  8]]


In [31]:
# Multiplicacion Matricial

C = A @ B
E = np.dot(A,B)

print (C)
print (E)

[[ 94 148]
 [ 34  60]]
[[ 94 148]
 [ 34  60]]


In [32]:
# Transpuesta

AT = A.T
BT = B.T

print(AT)
print(BT)

[[10  2]
 [ 6  5]]
[[ 7  4]
 [10  8]]


In [33]:
# Inversa

C = np.linalg.inv(A)
E = np.linalg.inv(B)

print(C)
print(E)

[[ 0.13157895 -0.15789474]
 [-0.05263158  0.26315789]]
[[ 0.5    -0.625 ]
 [-0.25    0.4375]]


Solo se puede cuando la matriz es cuadrada, es decir, nxn

In [34]:
# Determinante

detA = np.linalg.det(A)
detB = np.linalg.det(B)

print(detA)
print(detB)

37.99999999999999
16.000000000000007


In [35]:
# Rango (Grado de independencia)

rangoA = np.linalg.matrix_rank(A)
rangoB = np.linalg.matrix_rank(B)

print(rangoA)
print(rangoB)

2
2


In [37]:
# Traza

trazaA = np.trace(A)
trazaB = np.trace(B)

print(trazaA)
print(trazaB)

15
15


In [38]:
# Autovalores y autovectores

PA = np.linalg.eig(A)
PB = np.linalg.eig(B)

print(PA)
print(PB)

EigResult(eigenvalues=array([11.77200187,  3.22799813]), eigenvectors=array([[ 0.95904921, -0.66315547],
       [ 0.2832395 ,  0.74848168]]))
EigResult(eigenvalues=array([ 1.15571123, 13.84428877]), eigenvectors=array([[-0.86336694, -0.82522328],
       [ 0.50457657, -0.56480664]]))
