In [ ]:
import numpy as np

# Creacion de Arrays

a = np.array({1,2,3,4,5})
print("a. Desde una lista")
print(a)

b = np.zeros(5) # Crea un array de 5 ceros
b1 = np.zeros((2,3)) # Crea un array de dos filas y tres columnas
print("b. Arrays de ceros: ")
print(b)
print(b1)

c = np.ones(4) 
print("c. Array de unos ")
print(c)

d  = np.full(5, 7) # Cinco elementos con el valor 7
print("d. Array con un valor constante")
print(d)

e = np.arange(0,10,2) # del 0 al 9 con paso 2
print("e. Array con una secuencia de numeros")
print(e)

f = np.random.rand(3) # 3 valores entre 0 y 1 
f1 = np.random.randint(1,10,5) # 5 enteros entre 1 y 9
print("f. Array con numeros aleatorios")
print(f)
print(f1)

g = np.linspace(0,1,5) # 5 valores entre 0 y 1 
print("g. Array de valores espaciados")
print(g)

a. Desde una lista
{1, 2, 3, 4, 5}
b. Arrays de ceros: 
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
c. Array de unos 
[1. 1. 1. 1.]
d. Array con un valor constante
[7 7 7 7 7]
e. Array con una secuencia de numeros
[0 2 4 6 8]
f. Array con numeros aleatorios
[0.96832367 0.68419032 0.42817003]
[9 3 4 2 3]
g. Array de valores espaciados
[0.   0.25 0.5  0.75 1.  ]
