In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])


Estas operaciones se realizan en elemento a elemento.

In [3]:
# Suma
suma1 = a+b
suma2 = np.add(a,b)
print(suma1)
print(suma2)

[5 7 9]
[5 7 9]


In [4]:

# Resta
resta1 = a-b
resta2 = np.subtract(a,b)

print(resta1)
print(resta2)

[-3 -3 -3]
[-3 -3 -3]


In [6]:
# Multiplicacion
multiplicacion1 = a*b
multiplicacion2 = np.multiply(a,b)
print(multiplicacion1 )
print(multiplicacion2)

[ 4 10 18]
[ 4 10 18]


In [8]:
# Division
division1 = a/b
division2 = np.divide(a,b)

print(division1)
print(division2)

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


In [9]:
#Potencia
potencia1 = a**b
potencia2 = np.power(a,b)

print(potencia1)
print(potencia2)


[  1  32 729]
[  1  32 729]


In [10]:
#Modulo (resto)
modulo1 = a%b
modulo2 = np.mod(a,b)

print(modulo1)
print(modulo2)

[1 2 3]
[1 2 3]


Tambien puedes usar numeros escalares, por ejemplo, multiplicar todos los elementos del array por un 10. 

In [1]:
import numpy as np

a = np.array([1,2,3])

print(a+10)
print(a-10)
print(a*10)
print(a/10)
print(a**2)

[11 12 13]
[-9 -8 -7]
[10 20 30]
[0.1 0.2 0.3]
[1 4 9]
