Nivel 1 - Fundamentos de Array

In [15]:
import numpy as np

arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


1. Crear Arrays
A . Crear un array con los numeros del 1 al 10.
B. Crea otro con los numeros pares del 2 al 10

In [16]:
arr2 = np.arange(2,21,2)
print(arr2)

[ 2  4  6  8 10 12 14 16 18 20]


2. Propiedades
A. Averigua cuantos elementos tiene el array
B. Obten su forma (filas, columnas) y tipo de datos.

In [36]:
n = np.size(arr)
t = arr.dtype
f = arr.size
print(arr,n,t,fc)

n2 = np.size(arr2)
t2 = arr2.dtype
f2 = arr2.size
print(arr2,n2,t2,f2)

[1 2 3 4 5 6 7 8 9] 9 int64 9
[ 2  4  6  8 10 12 14 16 18 20] 10 int64 10


3. Operaciones Basicas
A. Suma 5 a cada elemento
B. Multiplica todos los valores por3.
C.Eleva cada elemento al cuadrado

In [39]:
a = arr + 5
print(a)

b = arr2 + 5
print(b)

[ 6  7  8  9 10 11 12 13 14]
[ 7  9 11 13 15 17 19 21 23 25]


In [40]:
a = arr * 3
print(a)

b = arr2 * 3
print(b)

[ 3  6  9 12 15 18 21 24 27]
[ 6 12 18 24 30 36 42 48 54 60]


In [41]:
a = arr ** 2
print(a)

b = arr2 ** 2
print(b)

[ 1  4  9 16 25 36 49 64 81]
[  4  16  36  64 100 144 196 256 324 400]
