In [1]:
import numpy as np

arr = np.arange(0,20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [2]:
numeros_pares = arr[ arr%2 == 0]
print(numeros_pares)

[ 0  2  4  6  8 10 12 14 16 18]


In [4]:
numeros_mayores = arr[arr > 10]
print(numeros_mayores)

[11 12 13 14 15 16 17 18 19]


In [7]:
combinacion = arr[(arr > 10) & (arr%2 == 0)]
print(combinacion)

[12 14 16 18]
