Nivel 2 - Arrays bidimensionales (matrices)

In [1]:
import numpy as np

arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
matriz = arr.reshape((3,3)) # A partir de un array crea una matriz 3x3
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
obten = matriz[1][2]
print(obten)

obten = matriz[1]
print(obten)

obten = matriz[2]
print(obten)


6
[4 5 6]
[7 8 9]


In [35]:
print(matriz.sum())
print(np.mean(matriz,axis=1))
print(matriz.max())
print(matriz.min())

45
[2. 5. 8.]
9
1
