In [47]:
import numpy as np

productos = ["Teclado", "Mouse", "Monitor", "Latop", "Auriculares"]
surcursales = ["Centro", "Norte", "Sur", "Este"]
stock = np.array([[12,15,8,10],[9,18,7,14],[5,11,6,9],[7,10,13,12],
                  [14,8,10,16]])



In [48]:
total_disponible = np.array([sum(n) for n in stock])
print(total_disponible)
print(np.vstack([productos,total_disponible]))

[45 48 31 42 48]
[['Teclado' 'Mouse' 'Monitor' 'Latop' 'Auriculares']
 ['45' '48' '31' '42' '48']]


In [49]:
nS = np.size(surcursales)
nP = np.size(productos)


total_por_producto = np.array([sum(stock[:,i]) for i in range(0,nS)])
print(total_por_producto)


[47 62 44 61]


In [50]:

# Se vendio un  teclado  en la sucursal del norte
stock[1,1] = stock[1,1] - 1
print(stock)

# Se vendio un producto de cada tipo en la sucursal del centro
stock[:,0] = stock[:,0] - 1
print(" ")
print(stock)

# Se compraron  tres monitores en todas las surcursales 
stock[2, :] = stock[2, :] - 3
print(" ")
print(stock)

# Hubo un aumento del 10% en stocks (Todas las sucursales)
stock = (stock * 1.10).astype(int)
print(" ")
print(stock)

# Condicion
stock[ stock > 15] -= 1



[[12 15  8 10]
 [ 9 17  7 14]
 [ 5 11  6  9]
 [ 7 10 13 12]
 [14  8 10 16]]
 
[[11 15  8 10]
 [ 8 17  7 14]
 [ 4 11  6  9]
 [ 6 10 13 12]
 [13  8 10 16]]
 
[[11 15  8 10]
 [ 8 17  7 14]
 [ 1  8  3  6]
 [ 6 10 13 12]
 [13  8 10 16]]
 
[[12 16  8 11]
 [ 8 18  7 15]
 [ 1  8  3  6]
 [ 6 11 14 13]
 [14  8 11 17]]
